apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: <namespace>
spec:
  template:
    spec:
      containers:
        - name: django-migrate
          image: artemzinukov/django-app_2:fc2a0ee3
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: app-secret
      restartPolicy: OnFailure